parameters:
    solution: ""
    config: ""

jobs:
- job:
  displayName: Building SPA App
  steps:

  - checkout: self

  - task: UseDotNet@2
    displayName: "dotnet 6.0.x"
    inputs:
      packageType: 'sdk'
      version: "6.0.x"
  
  - task: NuGetToolInstaller@1
    displayName: "install nuget"

  - task: NuGetCommand@2
    displayName: "nuget restore"
    inputs:
      restoreSolution: ${{ parameters.solution }}

  # - task: DotNetCoreCli@2
  #   displayName: "dotnet restore"
  #   inputs:
  #       command: restore
  #       projects: "${{ parameters.solution }}"

  # - task: DotNetCoreCli@2
  #   displayName: "dotnet build"
  #   inputs: 
  #       projects: "${{ parameters.solution }}"
  #       command: build
  #       zipAfterPublish: true
  #       arguments: '--configuration ${{ parameters.config }} --output "$(Build.ArtifactStagingDirectory)/$(Build.BuildId)"'

  # - task: DotNetCoreCli@2
  #   displayName: "dotnet test"
  #   inputs:
  #     command: test
  #     projects: "${{ parameters.solution }}"
  #     arguments: '--configuration ${{ parameters.config }}'

  - task: MSBuild@1
    inputs:
      solution: "${{ parameters.solution }}"
      msbuildArguments: '-p:PackageLocation="$(Build.ArtifactStagingDirectory)/$(Build.BuildId)";DeployOnBuild=true;PackageAsSingleFile=true'

  - task: PublishBuildArtifacts@1
    displayName: spa_app
    inputs:
        PathToPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: spa_app