parameters:
    solution: ""
    config: ""

jobs:
- job:
  displayName: Building SPA App
  steps:
  - checkout: self

  - task: DotNetCoreCli@2
    displayName: "dotnet restore"
    inputs:
        command: restore
        projects: "${{ parameters.solution }}"

  - task: DotNetCoreCli@2
    displayName: "dotnet build"
    inputs: 
        projects: "${{ parameters.solution }}"
        command: build
        arguments: '--configuration ${{ parameters.config }} --output "$(Build.ArtifactStagingDirectory)/$(Build.BuildId)"'

  - task: PublishBuildArtifacts@1
    displayName: spa_app
    inputs:
        PathToPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: spa_app