parameters:
  solution: ""
  config: ""

jobs:
- job: Test_App
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '${{ parameters.solution }}'
      arguments: '--configuration ${{ parameters.config }}'