name: "(API-Build)-$(Date:dd.MM.yyyy)-($(Rev:r))"

resources:
  repositories:
    - repository: asp_spa
      type: github
      name: iamguri/asp_spa_app
      endpoint: iamguri
      trigger:
        branches:
          include:
            - main
            - develop
            - feature

pool: Self-hosted

stages:
- stage: Build
  jobs: 
  - job: Build
    steps:
    - task: Bash@3
      displayName: Build
      inputs:
        targetType: inline
        script: |
          echo Build Stage

  - job: Test
    dependsOn : Build
    steps:
    - task: Bash@3
      displayName: Test
      inputs:
        targetType: inline
        script: |
         echo Test

  - job: Infrastructure
    dependsOn: 
      - Build
    steps: 
      - task: Bash@3
        displayName: "Infra Provisioning"
        inputs:
          targetType: inline
          script: |
            echo "Infra stage"
            
  - job: Deploy
    dependsOn: 
      - Build
      - Test
    steps:
      - task: Bash@3
        displayName: Deploy
        inputs:
          targetType: inline
          script: |
            echo Deploy