name: "(API-Build)-($(Date:dd.MM.yyyy))-($(Rev:r))"

resources:
  repositories:
    - repository: asp_spa
      type: github
      name: iamguri/asp_spa_app
      endpoint: iamguri
      trigger:
        branches:
          include:
            - main
            - develop
            - feature

pool: Self-hosted

stages:
- stage: Build_App
  displayName: Build_App
  variables:
    system.debug: true
    solutionFile: ./dotnet.csproj
    config: "Release"
    BuildPlatform: "Any CPU"

  jobs:
  - template: ./Templates/build-template.yml
    parameters:
      solutionFile: $(solution)
      config: $(config)

- stage: Test_App
  dependsOn : Build_App
  displayName: Test_App
  jobs:
  - job: Test
    steps:
    - task: Bash@3
      displayName: Test
      inputs:
        targetType: inline
        script: |
         echo Test

- stage: Infra_provisioning
  dependsOn: 
    - Build_App
    - Test_App
  jobs:
  - job: Infrastructure
    steps: 
      - task: Bash@3
        displayName: "Infra Provisioning"
        inputs:
          targetType: inline
          script: |
            echo "Infra stage"
